version: "3.8"

services:
  microhost:
    build: .
    container_name: microhost
    expose:
      - ${API_PORT}
    environment:
      - DOMAIN=${DOMAIN}
      - API_PORT=${API_PORT}
      - SERVER_URL=${SERVER_URL:-https://${DOMAIN}}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - CONSOLE_URL=${CONSOLE_URL:-http://${DOMAIN}:3000}
    volumes:
      - ./data:/app/data
      - ./apps:/var/www/apps
      - ./clamav:/var/lib/clamav
    networks:
      - dokploy-network
      - default
    restart: unless-stopped

  frontend:
    build:
      context: ./microhost-frontend
      args:
        - NEXT_PUBLIC_API_URL=${SERVER_URL:-https://${DOMAIN}}
    container_name: microhost-frontend
    expose:
      - 3000
    environment:
      - NEXT_PUBLIC_API_URL=${SERVER_URL:-https://${DOMAIN}}
    networks:
      - dokploy-network
      - default
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
