version: "3.8"

services:
  microhost:
    build: .
    container_name: microhost
    expose:
      - 80
    environment:
      - DOMAIN=${DOMAIN}
      - API_PORT=80
      - SERVER_URL=https://${DOMAIN}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
    volumes:
      - ./data:/app/data
      - ./apps:/var/www/apps
      - ./clamav:/var/lib/clamav
    restart: unless-stopped
